CREATE TABLE IF NOT EXISTS product (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                       name VARCHAR(255) NOT NULL,
    price INTEGER NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS member (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                      email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS wish (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    member_id BIGINT NOT NULL,
                                    product_id BIGINT NOT NULL,
                                    count INTEGER NOT NULL DEFAULT 1,
                                    PRIMARY KEY (id),
    FOREIGN KEY (member_id) REFERENCES member(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
    );