CREATE TABLE Product
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    price DOUBLE NOT NULL,
    imageUrl VARCHAR(255) NOT NULL
);

CREATE TABLE Users
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);
