spring:
  config:
    import: application-secret.yml

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql

  jpa:
    defer-datasource-initialization: true #Hibernate 초기화 후 data.sql 실행

jwt:
  expiration: 3600000 #1시간

logging:
  level:
    gift.authentication: debug