INSERT INTO product(name, price, image_url) VALUES ('Product 1', 1000, 'https://via.placeholder.com/150'),
                                                   ('Product 2', 2000, 'https://via.placeholder.com/250'),
                                                   ('Product 3', 3000, 'https://via.placeholder.com/350'),
                                                   ('Product 4', 4000, 'https://via.placeholder.com/450'),
                                                   ('Product 5', 5000, 'https://via.placeholder.com/550'),
                                                   ('Product 6', 6000, 'https://via.placeholder.com/650'),
                                                   ('Product 7', 7000, 'https://via.placeholder.com/750'),
                                                   ('Product 8', 8000, 'https://via.placeholder.com/850'),
                                                   ('Product 9', 9000, 'https://via.placeholder.com/950'),
                                                   ('Product 10', 10000, 'https://via.placeholder.com/1050'),
                                                   ('Product 11', 11000, 'https://via.placeholder.com/1150'),
                                                   ('Product 12', 12000, 'https://via.placeholder.com/1250'),
                                                   ('Product 13', 13000, 'https://via.placeholder.com/1350'),
                                                   ('Product 14', 14000, 'https://via.placeholder.com/1450'),
                                                   ('Product 15', 15000, 'https://via.placeholder.com/1550'),
                                                   ('Product 16', 16000, 'https://via.placeholder.com/1650'),
                                                   ('Product 17', 17000, 'https://via.placeholder.com/1750'),
                                                   ('Product 18', 18000, 'https://via.placeholder.com/1850'),
                                                   ('Product 19', 19000, 'https://via.placeholder.com/1950'),
                                                   ('Product 20', 20000, 'https://via.placeholder.com/2050'),
                                                   ('Product 21', 21000, 'https://via.placeholder.com/2150'),
                                                   ('Product 22', 22000, 'https://via.placeholder.com/2250'),
                                                   ('Product 23', 23000, 'https://via.placeholder.com/2350'),
                                                   ('Product 24', 24000, 'https://via.placeholder.com/2450'),
                                                   ('Product 25', 25000, 'https://via.placeholder.com/2550'),
                                                   ('Product 26', 26000, 'https://via.placeholder.com/2650'),
                                                   ('Product 27', 27000, 'https://via.placeholder.com/2750'),
                                                   ('Product 28', 28000, 'https://via.placeholder.com/2850'),
                                                   ('Product 29', 29000, 'https://via.placeholder.com/2950'),
                                                   ('Product 30', 30000, 'https://via.placeholder.com/3050'),
                                                   ('Product 31', 31000, 'https://via.placeholder.com/3150'),
                                                   ('Product 32', 32000, 'https://via.placeholder.com/3250'),
                                                   ('Product 33', 33000, 'https://via.placeholder.com/3350'),
                                                   ('Product 34', 34000, 'https://via.placeholder.com/3450'),
                                                   ('Product 35', 35000, 'https://via.placeholder.com/3550'),
                                                   ('Product 36', 36000, 'https://via.placeholder.com/3650'),
                                                   ('Product 37', 37000, 'https://via.placeholder.com/3750'),
                                                   ('Product 38', 38000, 'https://via.placeholder.com/3850'),
                                                   ('Product 39', 39000, 'https://via.placeholder.com/3950'),
                                                   ('Product 40', 40000, 'https://via.placeholder.com/4050'),
                                                   ('Product 41', 41000, 'https://via.placeholder.com/4150'),
                                                   ('Product 42', 42000, 'https://via.placeholder.com/4250'),
                                                   ('Product 43', 43000, 'https://via.placeholder.com/4350'),
                                                   ('Product 44', 44000, 'https://via.placeholder.com/4450'),
                                                   ('Product 45', 45000, 'https://via.placeholder.com/4550'),
                                                   ('Product 46', 46000, 'https://via.placeholder.com/4650'),
                                                   ('Product 47', 47000, 'https://via.placeholder.com/4750'),
                                                   ('Product 48', 48000, 'https://via.placeholder.com/4850'),
                                                   ('Product 49', 49000, 'https://via.placeholder.com/4950'),
                                                   ('Product 50', 50000, 'https://via.placeholder.com/5050');

INSERT INTO member(name, email, password) VALUES ('Member 1', 'member01@gmail.com', 'member010101');
INSERT INTO member(name, email, password) VALUES ('Member 2', 'member02@gmail.com', 'member020202');
INSERT INTO member(name, email, password) VALUES ('Member 3', 'member03@gmail.com', 'member030303');

INSERT INTO wish_product(member_id, product_id, quantity) VALUES (1, 1, 2);
INSERT INTO wish_product(member_id, product_id, quantity) VALUES (1, 2, 4);
INSERT INTO wish_product(member_id, product_id, quantity) VALUES (1, 3, 8);
INSERT INTO wish_product(member_id, product_id, quantity) VALUES (2, 2, 1);
