## 상품 관련
### 1. 상품조회
GET http://localhost:8080/api/products

### 2. 상품등록
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name" : "coffee",
  "imgUrl" : "test.jpg",
  "price" : 10000
}

### 3.상품 수정
PUT http://localhost:8080/api/products/1
Content-Type: application/json

{
  "name" : "coffeeeeeee",
  "imgUrl" : "test.jpg",
  "price" : 100
}

