### get wish list
GET http://localhost:8080/api/wishes
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJtZW1iZXJfaWQiOjEsIm1lbWJlcl90eXBlIjoiVVNFUiIsImlhdCI6MTcyMDI2ODY0MCwiZXhwIjoxNzIwNjI4NjQwfQ.O5tifuVCD0psDiZe0OEu9FfFmKAoGRBbL1fFs8_CoqtxAWUktAB0guST5xqC29gMpbiLVxmEd-6q54lPqpT-fA
Content-Type: application/json

### create wish
POST http://localhost:8080/api/wishes
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJtZW1iZXJfaWQiOjEsIm1lbWJlcl90eXBlIjoiVVNFUiIsImlhdCI6MTcyMDE5Mzg2NCwiZXhwIjoxNzIwNTUzODY0fQ.CcDSD68i-POYge1OFupP_zIiR5k1Z0He9ZrINknEeqrq3zjGhy1esRn7_BV3-CeHU5wGWY4z-ppl5v5_UN78_g
Content-Type: application/json

{
  "memberId": 1,
  "productId": 1,
  "productCount": 5
}

### update product
PUT http://localhost:8080/api/wishes/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJtZW1iZXJfaWQiOjEsIm1lbWJlcl90eXBlIjoiVVNFUiIsImlhdCI6MTcyMDE5Mzg2NCwiZXhwIjoxNzIwNTUzODY0fQ.CcDSD68i-POYge1OFupP_zIiR5k1Z0He9ZrINknEeqrq3zjGhy1esRn7_BV3-CeHU5wGWY4z-ppl5v5_UN78_g
Content-Type: application/json

{
  "memberId": 1,
  "productId": 2,
  "productCount": 10
}

### delete product
DELETE http://localhost:8080/api/wishes/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJtZW1iZXJfaWQiOjEsIm1lbWJlcl90eXBlIjoiVVNFUiIsImlhdCI6MTcyMDE5Mzg2NCwiZXhwIjoxNzIwNTUzODY0fQ.CcDSD68i-POYge1OFupP_zIiR5k1Z0He9ZrINknEeqrq3zjGhy1esRn7_BV3-CeHU5wGWY4z-ppl5v5_UN78_g
Content-Type: application/json