### GET request to example server
POST /members/products/add HTTP/1.1
content-type: application/json
host: localhost:8080

{
  "price": "15000",
  "name": "dolce",
  "image_url": "exampleurl.com"
}
###

POST /members/register HTTP/1.1
content-type: application/json
host: localhost:8080

{
  "email": "admin8@email.com",
  "password": "passwrod",
  "name": "Admin8",
  "role": "admin8"
}
###
POST /members/login HTTP/1.1
content-type: application/json
host: localhost:8080

{
  "email": "admin8@email.com",
  "password": "passwrod"
}
###
POST /wishlist/add HTTP/1.1
Authorization: Bearer POST /wishlist/add HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhZG1pbjhAZW1haWwuY29tIiwiaWF0IjoxNzIwODgzMzE0LCJleHAiOjE3MjA4ODU3MTR9.ERJQn3ykzmwmY0CpFSlxO_uVwD6iIA_cfAOa-FFTjlo
content-type: application/x-www-form-urlencoded
host: localhost:8080


productId: 77

####
POST /wishlist/add HTTP/1.1
Authorization: Bearer POST /wishlist/add HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhZG1pbjhAZW1haWwuY29tIiwiaWF0IjoxNzIwODg3NTA5LCJleHAiOjE3MjA4ODk5MDl9.VIuXdi9ZFQqsk9Pqnrg_07tdq1jibnmJq2slfllvvos
content-type: application/json
host: localhost:8080

{
  "productId": 78
}
####
POST /wishlist/add HTTP/1.1
Authorization: Bearer POST /wishlist/add HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwibmFtZSI6IkFkbWluOCIsInJvbGUiOiJhZG1pbjgiLCJpYXQiOjE3MjAyODk0NzUsImV4cCI6MTcyMDI5MTg3NX0.szKqd0WCaBlkF-fNi2LMkU6wvdyn-y5APpI3Ed9omYk
content-type: application/json
host: localhost:8080

{
  "member_id": 74,
  "product_id": 77,
  "product_name": "아메리가",
  "product_price": 10003
}
####
content-type: application/json
host: localhost:8080

{
  "member_id": 74,
  "product_id": 77,
  "product_name": "아메리가",
  "product_price": 10003
}
####
# @no-redirect
GET /wishlist/items HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiZW1haWwiOiJhZG1pbjhAZW1haWwuY29tIiwiaWF0IjoxNzIwNTU0MzgxLCJleHAiOjE3MjA1NTY3ODF9._St1Dim9BB9wQAEM4N748zJHDM7WGb4XRrQs-wb_Lqk
content-type: application/json
host: localhost:8080

{

}
#######

DELETE /wishlist/delete/6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiZW1haWwiOiJhZG1pbjhAZW1haWwuY29tIiwiaWF0IjoxNzIwNTcwNzk1LCJleHAiOjE3MjA1NzMxOTV9.lyrcE5jVzwmB3UKtAjKXAh-FvzX0O1RLAc9-urZo9jk
content-type: application/json
host: localhost:8080

{
  "id": 78
}
###
POST /products/add HTTP/1.1
content-type: application/json
host: localhost:8080

{
  "price": 1500,
  "name": "돌체",
  "image_url": "example"
}
###
DELETE /products/delete/2 HTTP/1.1
content-type: application/json
host: localhost:8080

{
  "id": 2
}
#####
