### GET request to example server
GET http://localhost:8080/api/users?size=3&page=1&sort=email&asc=false
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbGxsQGVtYWlsLmNvbSIsImlzcyI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzIwODU5MjQ1LCJleHAiOjE3MjA4NjI4NDV9.p7GAp7NKO1tfcvzaEH_rj8FtDWa_J1nOA4aWYi7d3hk

### signup request
POST http://localhost:8080/signup
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "aB12345678"
}

### account deletion request
DELETE http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbGxsQGVtYWlsLmNvbSIsImlzcyI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzIwODU5MjQ1LCJleHAiOjE3MjA4NjI4NDV9.p7GAp7NKO1tfcvzaEH_rj8FtDWa_J1nOA4aWYi7d3hk

### password change request
PATCH http://localhost:8080/api/password-change
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbGxsQGVtYWlsLmNvbSIsImlzcyI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzIwODU5MjQ1LCJleHAiOjE3MjA4NjI4NDV9.p7GAp7NKO1tfcvzaEH_rj8FtDWa_J1nOA4aWYi7d3hk
Content-Type: application/json

{
  "password": "aB4566666"
}

### signup request
POST http://localhost:8080/signup
Content-Type: application/json

{
  "email": "email0@email.com",
  "password": "aB12345678"
}

### login request
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "emailll@email.com",
  "password": "aB12345678"
}

### wish get request
GET http://localhost:8080/api/wishes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbGxsQGVtYWlsLmNvbSIsImlzcyI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzIwODU5MjQ1LCJleHAiOjE3MjA4NjI4NDV9.p7GAp7NKO1tfcvzaEH_rj8FtDWa_J1nOA4aWYi7d3hk


### wish post request
POST http://localhost:8080/api/wishes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbGxsQGVtYWlsLmNvbSIsImlzcyI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzIwODU5MjQ1LCJleHAiOjE3MjA4NjI4NDV9.p7GAp7NKO1tfcvzaEH_rj8FtDWa_J1nOA4aWYi7d3hk
Content-Type: application/json

{
  "userId": 5,
  "productId": 1
}

### wish delete request
DELETE http://localhost:8080/api/wishes/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbGxsQGVtYWlsLmNvbSIsImlzcyI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzIwODU5MjQ1LCJleHAiOjE3MjA4NjI4NDV9.p7GAp7NKO1tfcvzaEH_rj8FtDWa_J1nOA4aWYi7d3hk

### product post request
POST http://localhost:8080/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbGxsQGVtYWlsLmNvbSIsImlzcyI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzIwODU5MjQ1LCJleHAiOjE3MjA4NjI4NDV9.p7GAp7NKO1tfcvzaEH_rj8FtDWa_J1nOA4aWYi7d3hk
Content-Type: application/json

{
  "name": "dddd",
  "price": 2200,
  "imageUrl": "https://letsenhance.io/static/8f5e523ee6b2479e26ecc91b9c25261e/1015f/MainAfter.jpg"
}