### GET request to example server
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbGxsQGVtYWlsLmNvbSIsImlzcyI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzIwNzEwNjM1LCJleHAiOjE3MjA3MTQyMzV9.bqmYpCd8m_Cu5ke5K__ncIAETENYuzbZh62bd-QdXSE

### signup request
POST http://localhost:8080/signup
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "aB12345678"
}

### account deletion request
DELETE http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbGxsQGVtYWlsLmNvbSIsImlzcyI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzIwNzEwNjM1LCJleHAiOjE3MjA3MTQyMzV9.bqmYpCd8m_Cu5ke5K__ncIAETENYuzbZh62bd-QdXSE

### password change request
PATCH http://localhost:8080/api/password-change
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbGxsQGVtYWlsLmNvbSIsImlzcyI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzIwNzEwNjM1LCJleHAiOjE3MjA3MTQyMzV9.bqmYpCd8m_Cu5ke5K__ncIAETENYuzbZh62bd-QdXSE
Content-Type: application/json

{
  "password": "aB4566666"
}

### signup request
POST http://localhost:8080/signup
Content-Type: application/json

{
  "email": "emailll@email.com",
  "password": "aB12345678"
}

### login request
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "emailll@email.com",
  "password": "aB12345678"
}

### wish get request
GET http://localhost:8080/api/wishes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbGxsQGVtYWlsLmNvbSIsImlzcyI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzIwNzEwNjM1LCJleHAiOjE3MjA3MTQyMzV9.bqmYpCd8m_Cu5ke5K__ncIAETENYuzbZh62bd-QdXSE


### wish post request
POST http://localhost:8080/api/wishes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbGxsQGVtYWlsLmNvbSIsImlzcyI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzIwNzEwNjM1LCJleHAiOjE3MjA3MTQyMzV9.bqmYpCd8m_Cu5ke5K__ncIAETENYuzbZh62bd-QdXSE
Content-Type: application/json

{
  "userId": 5,
  "productId": 1
}

### wish delete request
DELETE http://localhost:8080/api/wishes/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbGxsQGVtYWlsLmNvbSIsImlzcyI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzIwNzEwNjM1LCJleHAiOjE3MjA3MTQyMzV9.bqmYpCd8m_Cu5ke5K__ncIAETENYuzbZh62bd-QdXSE

### product post request
POST http://localhost:8080/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbGxsQGVtYWlsLmNvbSIsImlzcyI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzIwNzEwNjM1LCJleHAiOjE3MjA3MTQyMzV9.bqmYpCd8m_Cu5ke5K__ncIAETENYuzbZh62bd-QdXSE
Content-Type: application/json

{
  "name": "dddd",
  "price": 2200,
  "imageUrl": "https://letsenhance.io/static/8f5e523ee6b2479e26ecc91b9c25261e/1015f/MainAfter.jpg"
}